---
- name: Setting up Fedora 37 workstation in plain mode
  hosts: plain
  roles: 
   - ssh
   - packages
   - firewall 
   - docker   
   - ghost-install
 
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo 


  pre_tasks:

    - name: Run pre-tasks
      include: includes/pre-tasks.yml 
  

  tasks:

    - name: Show reboot message to ensure that all configurations have been applied
      debug: 
        msg: Please reboot the target host / node before continuing, to ensure that all configurations have been applied
