---
- name: Setting up Fedora 37 workstation in developer mode
  hosts: developer
  roles:
   - packages   
   - ssh   
   - firewall       
   - docker
   - nix-install
   - ghost-install
   - certificates
   - haproxy
   #- deployment-ghost-block
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo 


  pre_tasks:

    - name: Run pre-tasks
      include: includes/pre-tasks.yml 
  
  vars:
    - ws_developer: true         #Only for install-developer-ws.yml . Keep it here.
##Vars for certificates. They can be moved to their respective hosts. Comment them out to skip the step.
    - ca_authority: true         # Only define when CA needs to be created
    - issue_certificate: true    # Only define when certificate needs to be issued

  tasks:

    - name: Show reboot message to ensure that all configurations have been applied
      debug: 
        msg: Please reboot the target host / node before continuing, to ensure that all configurations have been applied
