---
# tasks file for ssh

- name: Copying templates/sshd_config.j2 template to /etc/ssh/sshd_config
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Restart sshd

- name: Copy templates/jail.local.j2 to /etc/fail2ban/jail.local
  template:
    src: templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: Restart fail2ban

- name: Start and enable sshd
  service:
    name: sshd
    state: restarted
    enabled: yes

- name: Start and enable fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes
