---

    - name: Create certificate authority dir {{ ca_host_directory }}
      file:
        path: "{{ item }}"
        owner: "{{ super_user }}"
        group: "{{ super_user }}"
        state: directory
        mode: 0755
      with_items: 
        - ca_host_directory: ~/cert_authority
      become: true
      
    - name: Create private key with password protection
      community.crypto.openssl_privatekey:
        path: '{{ ca_host_directory }}/ca-certificate.key'

    - name: Create certificate signing request CSR for CA certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: '{{ ca_host_directory }}/ca-certificate.key'
        common_name: Ansible CA
        use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: ca_csr

    - name: Create self-signed CA certificate from CSR
      community.crypto.x509_certificate:
        path: '{{ ca_host_directory }}/ca-certificate.pem'
        csr_content: "{{ ca_csr.csr }}"
        privatekey_path: '{{ ca_host_directory }}/ca-certificate.key'
        provider: selfsigned


    - name: Adding CA self signed certificate to trusted certificates {{ trusted_cert_location }}
      shell: sudo cp {{ ca_host_directory }}/ca-certificate.pem {{ trusted_cert_location }}

