---
# tasks file for docker
  ## include from user_management for docker
  - include_vars: ../../user_management/vars/main.yml

  - name: Install docker ce system packages
    yum:
      name: "{{ docker_packages }}"
      state: latest
      use_backend: yum4
    become: true     


  - name: Starting docker and enabling it on boot
    systemd:
      name: docker
      state: started
      enabled: yes
    become: true  


  - name: adding users to docker group
    user:
      name: "{{ item }}"
      groups: "docker"
      append: true
    with_items: "{{ docker_users }}"
    become: true        